apiVersion: v1
kind: Service
metadata:
  name: function
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: function
    release: __release_tag__
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: function
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: function
      release: __release_tag__
  template:
    metadata:
      labels:
        app: function
        release: __release_tag__
    spec:
      containers:
        - name: function
          image: '__docker_registry_server__/data.stack:function.__release__'
          ports:
            - containerPort: 3030
          startupProbe:
            httpGet:
              path: /function/health/ready
              port: 3030
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 60
          env:
            - name: DS_MAX_JSON_SIZE
              value: "100kb"
            - name: DS_MAX_FILE_SIZE
              value: "5MB"
          envFrom:
          - configMapRef:
              name: config

